### ISSUE TITLE
Centos 7 使用 shadowvpn 问题求助

### ISSUE THREAD

**Issue by luckiss** [clowwindy/ShadowVPN#100]
在ubuntu上部署很方便，centos貌似现在只能自己编译。编译安装成功，运行以后进程里有shadowvpn，用netstat -lntp没发现监听端口。还有就是使用的firewalld要怎么对应shadowvpn server_up.sh等的iptables的配置。

**Comment by cj1324** [comment]
`netstat -anp`  你的netstat参数有问题， shadowvpn开的是udp端口。

**Comment by luckiss** [comment]
解决了。是我搞错了，在firewalld里把端口添加成TCP的了，改成UDP解决了。感觉楼上的。
