### ISSUE TITLE
ShadowVPN与MWAN3不兼容

### ISSUE THREAD

**Issue by yy1984** [clowwindy/ShadowVPN#101]
MWAN3还没有添加虚拟网卡，只有WAN一个端口，连接ShadowVPN后无法PING通10.7.0.1
禁用MWAN3后ShadowVPN就正常了。
client_up.sh中防火墙相关的脚本只有下面3句
iptables -t nat -A POSTROUTING -o $intf -j MASQUERADE
iptables -I FORWARD 1 -i $intf -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -I FORWARD 1 -o $intf -j ACCEPT

**Comment by clowwindy** [comment]
这个脚本只是示例，你需要根据自己网络情况修改。
