### ISSUE TITLE
Openwrt ShadowVpn problem

### ISSUE THREAD

**Issue by ddqp** [clowwindy/ShadowVPN#104]
首先很感谢作者，shadowvpn很不错。

我在openwrt上使用的时候，安装后，使用client脚本，流量还是无法通过shadowvpn出去。调试如下：
1. openwrt ping/mtr 8.8.8.8,都是不走VPS，
2. openwrt ping 10.7.0.1，没有问题，也就是和VPS想通，
3. 电脑可以上网，只是不能FQ
4. 服务器设置没有问题，因为用别的电脑的shadowvpn的客户端是可以用的。
5. 如果不使用client脚本，而采用LUCI设置后，是可以的，但是不知道如何停用，
To disable ShadowVPN, go to step 5 and change default route 0.0.0.0 from tun to wan.
我是pppoe的，没有第五步中的这个设置，如果把第五步的第一行修改了，就整个上不了网了。

谢谢
DDQP

**Comment by cj1324** [comment]
看样子你是在NAT配置环节出了问题，建议你多花点时间看看该项目的wiki.  或者尝试了解和调试iptables规则。

**Comment by ddqp** [comment]
嗯，好的，谢谢啊，我反正经常就是，上述情况，哪怕是全新刷的路由器，装了shadowvpn也是这样，必须要重启多次才能好。
