### ISSUE TITLE
连接方式不支持域名，请求添加主机DNS解析的功能

### ISSUE THREAD

**Issue by testcaoy7** [clowwindy/ShadowVPN#106]
我的VPS的IP地址是动态分配的，经常会变，只有域名是固定的
在客户端conf的“server=”字段中，如果填写的是域名，就会出错

『Windows，MinGW编译版本的错误信息』
路由添加失败：参数错误
vpn.c:515 sendto: 套接字操作尝试一个无法连接的主机

如果把域名换成临时分配的公网IP，那么就又可以连了，可见目前ShadowVPN缺乏DNS解析的功能

**Comment by gandalfwong** [comment]
有可能是你的dns服务器设为8.8.8.8等墙外服务器， 因为vpn还没建立，dns请求失败。
如果你用的是dnsmasq可以按域名设定dns服务器，例如 server=/你的域名/114.114.114.114，前提是你要确保vpn建立前可以访问114.114.114.114

**Comment by testcaoy7** [comment]
也就是说目前ShadowVPN的逻辑是先连上VPN，再用配置文件中设置的DNS服务器进行域名解析？

**Comment by clowwindy** [comment]
无状态 VPN，无法支持。
