### ISSUE TITLE
centos7服务端启动脚本iptables规则的问题

### ISSUE THREAD

**Issue by 70599** [clowwindy/ShadowVPN#108]
我发现在centos7部署服务端后没法使用，后来想起centos7开始使用firewalld代替iptables。
打开服务端启动脚本server_up.sh，发现里面有iptables规则。

firewalld、iptables不能并用，可以指点一下firewalld的规则该怎么写吗？

**Comment by bitwing** [comment]
如果不是一定要用 Firewalld 的話建議用 Systemd 禁用掉，重新啓用 iptables
