### ISSUE TITLE
route table reset by system every time when network gets changed

### ISSUE THREAD

**Issue by hhaoyan** [clowwindy/ShadowVPN#111]
Sometimes when network gets changed, e.g. when closing and opening my laptop, system routing table will be reset by system. It would be better if shadowVPN can be aware of this and change them in response.

**Comment by clowwindy** [comment]
You need to restart ShadowVPN after such changes. This is done via [hotplug.d](https://github.com/clowwindy/ShadowVPN/blob/master/samples/30-shadowvpn) on OpenWRT. I don't how to do do it on your system, but you can find it out.
