### ISSUE TITLE
apt source authentication?

### ISSUE THREAD

**Issue by riobard** [clowwindy/ShadowVPN#116]
Debian/Ubuntu complains that the ShadowVPN package cannot be authenticated. Is there anyway to verify the source/package?

**Comment by clowwindy** [comment]
Well, to silent the complaints, we need to sign the package with a GPG key. http://shadowsocks.org/en/download/servers.html

But I think it's not a problem if we stick to https and we are the only distributor.

```
deb https://shadowvpn.org/debian wheezy main
```

**Comment by riobard** [comment]
https solution does not work right now. `apt update` complains 

    gnutls_handshake() failed: Handshake failed

**Comment by riobard** [comment]
Additionally, GPG key needs to be distributed via https. 

    $ curl https://shadowsocks.org/debian/1D27208A.gpg
    curl: (51) SSL: no alternative certificate subject name matches target host name 'shadowsocks.org'

**Comment by clowwindy** [comment]
https should work for shadowvpn.org, not shadowsocks.org.

**Comment by riobard** [comment]
On Ubuntu 14.04 `apt update` complains

    Ign https://shadowvpn.org wheezy/main Translation-en
    Err https://shadowvpn.org wheezy/main amd64 Packages
      gnutls_handshake() failed: Handshake failed
    Err https://shadowvpn.org wheezy/main i386 Packages
      gnutls_handshake() failed: Handshake failed

**Comment by clowwindy** [comment]
Oh, there's an compatibility issue with the free CloudFlare SSL that I use. Since distribution is not my current focus, I guess we'll just leave the problem there.

**Comment by clowwindy** [comment]
https://github.com/clowwindy/ShadowVPN/commit/17dc09c007b5f77f47d41e0e5151908587882cfe
