### ISSUE TITLE
要让shadowVPN正常工作，服务器端需要开放哪些端口？

### ISSUE THREAD

**Issue by hxhxd** [clowwindy/ShadowVPN#121]
好像仅工作端口是明显不够的，但又不知道需要哪些端口。
直接ALL开放，就能正常用的。

谢谢。

**Comment by 70599** [comment]
“好像”？
我开放了ssh、shadowvpn端口的入站请求。出站全允许。工作正常。

**Comment by hxhxd** [comment]
不是“好像”，就是不行。 已经验证多次

**Comment by hxhxd** [comment]
现在网络出故障了，断开shadowvpn就没法上网了，ping不通外网IP。 无法解析地址。 QQ里点对点聊天可以，但发图片传文件等都不能用

**Comment by 70599** [comment]
“好像”是你自己说的。
参考本项目的FAQ检查一下吧。
直接回答你主题的问题的话就是“没有需要额外开放的端口”。

**Comment by Pentiumluyu** [comment]
不需要开放额外的端口。断开shadowvpn之后无法上网应该是路由表的问题。
