### ISSUE TITLE
apt-get install does not work on amazon aws

### ISSUE THREAD

**Issue by dangelization** [clowwindy/ShadowVPN#129]
其实就是report一下，自己用deb安装其实也可以，但是问题post出来还是希望有大侠看看，我技术不太好搞不定。

使用的是 amazon aws 的 ubuntu 12.04 amd64，
添加 deb http://shadowvpn.org/debian wheezy main 是顺利的

但是sudo apt-get update 会出现以下error：

Err https://shadowvpn.org wheezy/main amd64 Packages
  gnutls_handshake() failed: Handshake failed
Ign https://shadowvpn.org wheezy/main Translation-en_US
Ign https://shadowvpn.org wheezy/main Translation-en
Fetched 1,903 kB in 4s (438 kB/s)
W: Failed to fetch https://shadowvpn.org/debian/dists/wheezy/main/binary-amd64/Packages  gnutls_handshake() failed: Handshake failed

E: Some index files failed to download. They have been ignored, or old ones used instead.

我google了一下，发现并且试验了下面两个方案，但是都不能修复问题。
http://askubuntu.com/questions/186847/error-gnutls-handshake-failed-when-connecting-to-https-servers
http://stackoverflow.com/questions/13524242/error-gnutls-handshake-failed-git-repository

这样的话就没办法使用apt-get install shadowvpn安装了，我最后直接使用deb安装的。

**Comment by clowwindy** [comment]
可以把 https 改成 http 试一下。

**Comment by dangelization** [comment]
搞定了，原来已经改成http了
