### ISSUE TITLE
OpenWrt Luci can't see the routes list the new script files 

### ISSUE THREAD

**Issue by phoenixxie0** [clowwindy/ShadowVPN#130]
While I use the new client script. The OpenWrt Route cannot get right routes list on the web Luci.
And the "net" in the client.conf should be removed to client_up.conf ?

**Comment by clowwindy** [comment]
Did you mean the master branch? It's not released yet. It won't work with existing release versions.

**Comment by xseven007** [comment]
Thx , I will follow up
