### ISSUE TITLE
About OpenVZ and new script files

### ISSUE THREAD

**Issue by cdpwdmp** [clowwindy/ShadowVPN#135]
昨天我发了一个Pull request https://github.com/clowwindy/ShadowVPN/pull/134
其中一部分是我把server_up.sh和server_down.sh里面的gw_intf=$(ip route show 0/0 | awk '{print $5}')
改成了gw_intf=$(ip route show 0/0 | awk '{print $3}')，现在我改回去了
昨天我只在我的OpenVZ VPS(CentOS 7)上测试了，结果为：
ip route show 0/0 | awk '{print $3}'
venet0
ip route show 0/0 | awk '{print $5}'
link

但是今天我又在本地的VMware中测试了Debian 8，CentOS 7，Fedora 22 Server
然后CentOS 和 Fedora的结果都是
ip route show 0/0 | awk '{print $3}'
10.0.0.1
ip route show 0/0 | awk '{print $5}'
eno167777xx
Debian是
ip route show 0/0 | awk '{print $3}'
10.0.0.1
ip route show 0/0 | awk '{print $5}'
eth0

所以我的OpenVZ的VPS可能是有点特殊吧
但是0.1.6 Release中的老方法
gw_intf=`ip route show | grep '^default' | sed -e 's/.* dev \([^ ]*\).*/\1/'`
无论是在我的VPS还是在本地各种系统中都可以获得正确的Interface
也许这是一个兼容性更好的方法

**Comment by clowwindy** [comment]
`samples` 里的文件只是示例，供用户自己修改的。因为这些脚本没有办法兼容任意系统，我们也没有精力维护不同系统的脚本，我们目前的兴趣只在 VPN 程序本身。

**Comment by XiaoxiaoPu** [comment]
最通用的方法：
```bash
ip route add $server $(ip route get $server | head -n 1)
```
