### ISSUE TITLE
关于服务器端的架设问题

### ISSUE THREAD

**Issue by McContax** [clowwindy/ShadowVPN#154]
用的是ubuntu，通过git把源码加载到本地然后编译好安装好之后启动程序
然后到log文件查看会出现这样的情况！
Sun Jan 10 16:35:46 2016 vpn.c:102 open: No such file or directory
Sun Jan 10 16:35:46 2016 can not open /dev/net/tun
Sun Jan 10 16:35:46 2016 failed to create tun device
请问怎么解决

**Comment by sdysj** [comment]
你个逗逼
![sb](http://md.ytmer.com/uploads/allimg/150722/1-150H2124Z1S5.jpg)

**Comment by McContax** [comment]
@sdysj 并没有找到解决方法！！！？

**Comment by HarukaMa** [comment]
Make sure your VPS provides TUN/TAP devices. Contact the provider or enable it in the panel.

iPhoneから送信

H28/01/10 17:42、Mass Carl <notifications@github.com> のメッセージ:

**Comment by McContax** [comment]
@HarukaMa thanks and I will have a try

**Comment by aa65535** [comment]
```sh
mkdir -p /dev/net
mknod /dev/net/tun c 10 200
chmod 0666 /dev/net/tun
```

**Comment by McContax** [comment]
@aa65535 按你的说法做了，解决了第一条问题，但是出现tun0无法设定的情况，这个可能还是会和VPS的类型有关。错误日志如下：
Mon Jan 11 08:20:44 2016 vpn.c:119 ioctl[TUNSETIFF]: Operation not permitted
Mon Jan 11 08:20:44 2016 can not setup tun device: tun0
Mon Jan 11 08:20:44 2016 failed to create tun device
