### ISSUE TITLE
Fails to work every few days

### ISSUE THREAD

**Issue by hfcorriez** [clowwindy/ShadowVPN#36]
我用的 0.11，用了这么长时间，几乎每隔两天就出现这个情况。我之前提过 #11，后来去做了手动设置，不知道跟这有木有关系。出问题的时候不管如何重启 shadowvpn、chindns、dnsmasq 都不行正常工作，只好去换个服务器，我有两台服务器，所以就每隔两天换个 IP 就正常了。

能判断是哪里出了问题么，还是升级最新就好了？最新的 openwrt 还是要手动去配置么？

**Comment by DarkLink** [comment]
同样的问题，一段时间之后VPS的IP可以ping通，但是10.7.0.1就不行了。
注意到一个细节就是当10.7.0.1不通的时候，traceroute 到VPS的IP无法成功，然后当能够成功traceroute到VPS的IP的时候，就继续可用了。不知道是不是普遍现象以及是否有比较合适的措施?

**Comment by Pentiumluyu** [comment]
我觉得比较像是ISP或者墙的问题。具体表现为使用某端口一段时间后，丢包率变得很高，重启shadowvpn也没有用，换端口后症状解决。但是隔一段时间后再使用之前用过的、丢包严重的端口也不会出现丢包率高的问题。3724和4000端口都会这样。
