### ISSUE TITLE
Move Configuration to *.conf

### ISSUE THREAD

**Issue by lsylsy2** [clowwindy/ShadowVPN#55]
由 https://github.com/clowwindy/ShadowVPN/issues/51 而来，up/down.sh更多的是应该提供给高级用户实现自定义功能的，而“设置MTU”、“变更默认网关”等等并不属于“自定义”的内容，它们还是由C语言直接调用系统命令、或者由shadowvpn根据配置文件自动生成一个shell脚本。
新开一个issue，是想把有需求移到conf中，简化配置难度的所有配置项都列出来，做一个整合。

- ip_forward

  服务器会一直开启该设置，客户端当作为“路由器”时，无论是否使用VPN都会一直开启，作为普通终端时都会关闭。

- ifconfig IP、MTU

  双端IP应当在conf中可以设置，至少像MTU一样设置一个变量，以保证修改不会遗漏；然后这两项都可以由C语言直接调用；
在 https://github.com/clowwindy/ShadowVPN/issues/51 中提到“脚本里可以读所有配置变量，把脚本里的 IP 挪到配置文件里 ip=x.x.x.x，在脚本里读 $ip 变量就可以了。”，这个其实很有必要。

  同时，对于 https://github.com/clowwindy/ShadowVPN/issues/53 的情况，可考虑提供一个小utility，提供MTU的测量与设置功能。

- iptables

  iptables可以考虑提供一个开关，让用户选择是否需要NAT上网，或者只需要建立隧道；

- chnroute

  在 https://github.com/clowwindy/ShadowVPN/issues/1 与 https://github.com/clowwindy/ShadowVPN/issues/24 中，都提到了各种chnroute的设置，对于“普通用户”，尤其是安装在openwrt的用户，与chinadns、chnroute搭配是很高的需求；将其整合进主线，提供一个配置参数，设定该参数时指定一定的IP段或者一个包含IP段的文件（shadowXXX、chinadns系列软件最好能格式互通，共用同一个文件），自动处理chnroute的设置与释放，同时把ipset之类的优化也加上。

将设置项移入统一的conf，这样也方便shadowvpn对openwrt提供一个uci接口；至于设置路由之类，隐藏进程序内部后，可以直接调用route，也可以再反向调用openwrt的各种接口。

相关open状态的issue：
https://github.com/clowwindy/ShadowVPN/issues/1 关于chnroute
https://github.com/clowwindy/ShadowVPN/issues/24 chnroute讨论
https://github.com/clowwindy/ShadowVPN/issues/51 关于conf的，可以标记为合并入这个
https://github.com/clowwindy/ShadowVPN/issues/53 MTU值

**Comment by clowwindy** [comment]
办了条 100 M 的宽带，现在 CPU 是主要瓶颈了，我觉得这个问题可以再讨论一下，不过现在重点不一样了，所以另开一个 issue。

https://github.com/clowwindy/ShadowVPN/issues/93

**Comment by suiyuinfo** [comment]
把Svpn路由器做主路由，下挂一个高性能路由器，svpn 10M CPU（ar9331）占用不超过30%。
