### ISSUE TITLE
Ping value

### ISSUE THREAD

**Issue by cdpwdmp** [clowwindy/ShadowVPN#79]
在开启shadowvpn的时候，有一定的几率，感觉是50%
我ping vps上shadowvpn的TUN网卡ip（比如10.7.0.1）的ping值比我直接ping vps的ip要高出10左右
经常要重新多开几次才能得到正常的ping值

是日本vps，基本上全天ping都保持在大约110
联通4.5M ADSL

我的系统是WIN8.1，shadowvpn客户端是在debian上编译的
TAP驱动是tap-windows-9.21.1.exe

release里面的源代码也试过，也是一样的结果

补充一下，这个问题在vmware player里面虚拟的debian上也会发生，这个vmware player是装在windows上的，不过我的PC上现在没有装debian所以对于从实机启动的linux会不会这样我也不知道

**Comment by clowwindy** [comment]
OpenWRT 重现不了这个问题。10ms 的波动本来也很正常。

```
64 bytes from 10.7.0.1: icmp_seq=0 ttl=62 time=112.714 ms
64 bytes from 10.7.0.1: icmp_seq=1 ttl=62 time=106.385 ms
64 bytes from 10.7.0.1: icmp_seq=2 ttl=62 time=109.030 ms
64 bytes from 10.7.0.1: icmp_seq=3 ttl=62 time=102.503 ms
64 bytes from 10.7.0.1: icmp_seq=4 ttl=62 time=104.186 ms
64 bytes from 10.7.0.1: icmp_seq=5 ttl=62 time=108.065 ms
```

**Comment by cdpwdmp** [comment]
好吧，倒也不算是什么大问题
不过那应该不算是波动，是很稳定的区别
直接ping vps：
Reply from xx.xxx.113.xxx: bytes=32 time=113ms TTL=51
Reply from xx.xxx.113.xxx: bytes=32 time=113ms TTL=51
Reply from xx.xxx.113.xxx: bytes=32 time=116ms TTL=51
Reply from xx.xxx.113.xxx: bytes=32 time=113ms TTL=51
Reply from xx.xxx.113.xxx: bytes=32 time=113ms TTL=51
Reply from xx.xxx.113.xxx: bytes=32 time=114ms TTL=51
Reply from xx.xxx.113.xxx: bytes=32 time=115ms TTL=51
Reply from xx.xxx.113.xxx: bytes=32 time=111ms TTL=51
Reply from xx.xxx.113.xxx: bytes=32 time=115ms TTL=51

高出10ms：
Reply from 10.7.0.1: bytes=32 time=126ms TTL=64
Reply from 10.7.0.1: bytes=32 time=123ms TTL=64
Reply from 10.7.0.1: bytes=32 time=123ms TTL=64
Reply from 10.7.0.1: bytes=32 time=124ms TTL=64
Reply from 10.7.0.1: bytes=32 time=125ms TTL=64
Reply from 10.7.0.1: bytes=32 time=125ms TTL=64
Reply from 10.7.0.1: bytes=32 time=127ms TTL=64
Reply from 10.7.0.1: bytes=32 time=122ms TTL=64
Reply from 10.7.0.1: bytes=32 time=125ms TTL=64
Reply from 10.7.0.1: bytes=32 time=123ms TTL=64
Reply from 10.7.0.1: bytes=32 time=124ms TTL=64

正常：
Reply from 10.7.0.1: bytes=32 time=114ms TTL=64
Reply from 10.7.0.1: bytes=32 time=114ms TTL=64
Reply from 10.7.0.1: bytes=32 time=115ms TTL=64
Reply from 10.7.0.1: bytes=32 time=116ms TTL=64
Reply from 10.7.0.1: bytes=32 time=114ms TTL=64
Reply from 10.7.0.1: bytes=32 time=115ms TTL=64
Reply from 10.7.0.1: bytes=32 time=115ms TTL=64
Reply from 10.7.0.1: bytes=32 time=115ms TTL=64
Reply from 10.7.0.1: bytes=32 time=116ms TTL=64
Reply from 10.7.0.1: bytes=32 time=113ms TTL=64
Reply from 10.7.0.1: bytes=32 time=114ms TTL=64
Reply from 10.7.0.1: bytes=32 time=115ms TTL=64
