### ISSUE TITLE
允许两倍发包？

### ISSUE THREAD

**Issue by clowwindy** [clowwindy/ShadowVPN#81]
原丢包率 `c`
如果以一定概率 `p` 两倍发包
现丢包率 `c' = c ^ (1 +p)`

```
c = 0.1, p = 0.2, c' = 0.063
c = 0.1, p = 0.5, c' = 0.031
c = 0.1, p = 0.8, c' = 0.015
c = 0.1, p = 0.8, c' = 0.010

c = 0.2, p = 0.2, c' = 0.145
c = 0.2, p = 0.5, c' = 0.089
c = 0.2, p = 0.8, c' = 0.055
c = 0.2, p = 0.8, c' = 0.04
```

**Comment by lsylsy2** [comment]
这不就是net_speeder干的事情么
无脑的带来两倍流量不见得是好事，副作用是可用带宽只有50%（比如宽带物理带宽只有8M，那么实际最大就只剩4M）；调整上层协议（比如修改tcp拥塞控制，或者使用商业软件如锐速之类）才是正道。

**Comment by myliyifei** [comment]
vpn是udp。。你说的都是tcp调优
2015年1月13日 下午2:30于 "lsylsy2" <notifications@github.com>写道：

**Comment by lsylsy2** [comment]
@myliyifei UDP本来就是一个没有可靠性的协议，我们用VPN也是在上面跑TCP之类的协议；
我自己是跑的裸的shadowvpn，然后在隧道内部用锐速优化（设置锐速接管tun接口）；
而如果
总之我个人不支持在shadowvpn层面做太多的网络优化。（一个极端例子是openvpn over TCP）

要指出一点，tun接口的tcp拥塞控制也是受全局影响的（可以设置hybla、htcp、换锐速之类），不知道是不是之前没有注意到。

**Comment by clowwindy** [comment]
VPN 要改 cc 算法只能找 Google 把 YouTube 服务器上的 cc 算法给改了

**Comment by clowwindy** [comment]
实际观察到的丢包情况大部分不是概率性的随机丢包，而是间歇性全丢或全不丢，所以无解。

**Comment by myliyifei** [comment]
是gfw干扰还是运营商的流量整形呢  需要我们配合观察么
2015年1月16日 上午11:20于 "clowwindy" <notifications@github.com>写道：

**Comment by cj1324** [comment]
我公司网络也遇到类似问题，几乎无法使用。
家里就正常工作。

**Comment by clowwindy** [comment]
线路问题，只能换机房。国内找个好点的机房做中转会好一点，但国内流量普遍很贵。

**Comment by 70599** [comment]
@lsylsy2 “设置锐速接管tun接口”就是把锐速配置文件里的accif设置成shadowvpn的tun吗（我的是tun0）？
还有什么推荐的设置吗？
