### ISSUE TITLE
Suggestion about changing route

### ISSUE THREAD

**Issue by limifly** [clowwindy/ShadowVPN#83]
在现有版本的shadowvpn中，连接建立后会将默认网关更改到10.7.0.1，但是这样做的坏处是需要记录原来的网关地址，断开时需要恢复。但是client端的shadowvpn程序如果没有正常关闭，默认网关没有恢复的话，用户可能会丢失到client的连接。

我以前用OpenVPN时，一般是添加两条路由，0.0.0.0/1和128.0.0.0/1，它们相当于0.0.0.0/0，但是默认的0.0.0.0/0还在路由表中，如果vpn没有正常关闭，系统仍然能找到这条路由。

欢迎探讨这样做的利弊。

**Comment by clowwindy** [comment]
shadowvpn 是无连接的，一般不会非正常关闭。如果关闭了，视作 bug。

**Comment by zhongchaoqian** [comment]
The routing table in `samples/darwin/darwin_client_up.sh` is configured this way.

```sh
# change routing table
echo changing default route
route add -net 128.0.0.0 $remote_tun_ip -netmask 128.0.0.0
route add -net 0.0.0.0 $remote_tun_ip -netmask 128.0.0.0
route add -net $remote_tun_ip $orig_gw -netmask 255.255.255.255
```

Should this be modified?
