### ISSUE TITLE
'sudo tcpdump -i tun0' on server showed the expected inbound traffic, but still unable to use VPN.

### ISSUE THREAD

**Issue by enihcam** [clowwindy/ShadowVPN#84]
'sudo tcpdump -i tun0' on server showed the expected inbound traffic, but still unable to use VPN.

the server is build on Azure US, and I made sure the ip_fowarding = 1 on server. what configuration should I check next?

**Comment by enihcam** [comment]
I then use 'sudo tcpdump -i tun0 -P in' on client and can see the expected HTTP responses. however, it cannot be routed+forwarded to wlan0 (my local wireless network). any ideas?

here's my iptables on client:
# Generated by iptables-save v1.4.21 on Fri Jan 23 00:35:44 2015
*mangle
:PREROUTING ACCEPT [19:1277]
:INPUT ACCEPT [18:1152]
:FORWARD ACCEPT [1:125]
:OUTPUT ACCEPT [12:1154]
:POSTROUTING ACCEPT [13:1279]
:FWMARK - [0:0]
-A PREROUTING -i wlan0 -j FWMARK
-A FWMARK -m set ! --match-set chnroute dst -j MARK --set-xmark 0xffff/0xffffffff
COMMIT
# Completed on Fri Jan 23 00:35:44 2015
# Generated by iptables-save v1.4.21 on Fri Jan 23 00:35:44 2015
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [1:122]
:POSTROUTING ACCEPT [1:122]
-A POSTROUTING -s 192.168.1.0/24 -o ppp0 -j MASQUERADE
-A POSTROUTING -o tun0 -j MASQUERADE
COMMIT
# Completed on Fri Jan 23 00:35:44 2015
# Generated by iptables-save v1.4.21 on Fri Jan 23 00:35:44 2015
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [20:3058]
:TCP - [0:0]
:UDP - [0:0]
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -i wlan0 -j ACCEPT
-A INPUT -m conntrack --ctstate INVALID -j DROP
-A INPUT -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -m conntrack --ctstate NEW -j TCP
-A INPUT -p udp -m conntrack --ctstate NEW -j UDP
-A INPUT -p tcp -m recent --set --name TCP-PORTSCAN --mask 255.255.255.255 --rsource -j REJECT --reject-with tcp-reset
-A INPUT -p udp -m recent --set --name UDP-PORTSCAN --mask 255.255.255.255 --rsource -j REJECT --reject-with icmp-port-unreachable
-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i wlan0 -j ACCEPT
-A FORWARD -i tun0 -j ACCEPT
-A FORWARD -s 192.168.1.0/24 -o ppp0 -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
-A TCP -p tcp -m recent --update --seconds 60 --name TCP-PORTSCAN --mask 255.255.255.255 --rsource -j REJECT --reject-with tcp-reset
-A UDP -p udp -m recent --update --seconds 60 --name UDP-PORTSCAN --mask 255.255.255.255 --rsource -j REJECT --reject-with icmp-port-unreachable
COMMIT
# Completed on Fri Jan 23 00:35:44 2015

**Comment by linhua55** [comment]
for wireless network,I advice you to test your real mtu value. for reference：MTU of PPPoE #53 
for windows
ping -f -l 1472  your-vps-ip
for linux
ping -s 1472   your-vps-ip
for example,my mtu is 1452,and the mtu value in client.conf  should be 1452-20-8-24=1400
