### ISSUE TITLE
Create a Build Matrix for OpenWRT

### ISSUE THREAD

**Issue by clowwindy** [clowwindy/ShadowVPN#85]
https://jenkins.shadowvpn.org/job/ShadowVPN/

**Comment by cj1324** [comment]
申请jenkins平台上的管理权限。我可以抽时间改进CI脚本。

**Comment by clowwindy** [comment]
Done.

**Comment by cj1324** [comment]
Done.

**Comment by clowwindy** [comment]
目前应该基本满足需求，过段时间看看能不能做到半自动 release 新版。

**Comment by cj1324** [comment]
可以利用 `参数化构建过程`  选项配合手动指定参数，进行半自动构建发布。

**Comment by clowwindy** [comment]
对，我也是这么想的。
