### ISSUE TITLE
Openwrt预编译版可不可以加入一个x86版本

### ISSUE THREAD

**Issue by paperrabbit** [clowwindy/ShadowVPN#86]
openwrt官方有给virtualbox虚拟机可使用x86版本(12.09)。
可以不可以预编译一个对应的版本呢？

**Comment by cj1324** [comment]
目前jenkins平台，已经能够生成x86的ipk文件了。需要打通发布渠道。 @clowwindy

**Comment by paperrabbit** [comment]
thanks!
