### ISSUE TITLE
Windows 运行时出现 tunip not set in config file

### ISSUE THREAD

**Issue by HougeLangley** [clowwindy/ShadowVPN#91]
请教作者，我采用作者的方法在 Linux 下成功编译了win x64 的版本，运行过程中出现 tunip not set in confilg file.

我是不是需要修改 client.conf 中某个选项。希望朋友有所指导。

**Comment by aa65535** [comment]
Windows 需要指定 tun ip
使用这里的配置文件 https://github.com/clowwindy/ShadowVPN/tree/master/samples/windows
