### ISSUE TITLE
ShadowVPN 不能使用，求排查问题方法

### ISSUE THREAD

**Issue by 70599** [clowwindy/ShadowVPN#92]
症状：所有国外网站等待一段时间后连接被重置。
方案是@aa65535的plan6。
chinadns的上游服务器是：isp dns,8.8.8.8
ShadowVPN的mtu：服务端1448、客户端1440

已参考 https://github.com/clowwindy/ShadowVPN/wiki/FAQ 的 5.general diagnose steps:

on client ping server real IP
正常。

on client ping server VPN IP 10.7.0.1
正常。

on client traceroute 8.8.8.8 make sure it goes through 10.7.0.1
第一跳就是10.7.0.1。

on client ping 8.8.8.8; on server sudo tcpdump -i tun0 see if any packet arrives
运行tcpdump -i tun0后，刷出大量来自 10.7.0.2（客户端VPN IP）的信息。

you can also run sudo tcpdump host 8.8.8.8 or sudo tcpdump port 53 etc on the client or server
在客户端试图打开国外域名，服务端运行tcpdump host 8.8.8.8，看起来有相应的反应。

on server netstat -nr and ifconfig check if your wan is eth0 if not, update server_*.sh
ifconfig中eth0的ip是VPS的公网IP。

on client netstat -nr and ifconfig check if your lan is eth0. if not, update client_*.sh
这一步不太确定，ifconfig结果是：
br-lan Link encap:Ethernet HWaddr 10:6F:3F:29:70:CA
inet addr:192.168.1.1 Bcast:192.168.1.255 Mask:255.255.255.0
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:63127 errors:0 dropped:131 overruns:0 frame:0
TX packets:65064 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:0
RX bytes:17314018 (16.5 MiB) TX bytes:44819022 (42.7 MiB)

eth0 Link encap:Ethernet HWaddr 10:6F:3F:29:70:CA
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:63773 errors:0 dropped:132 overruns:0 frame:0
TX packets:65122 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:18216299 (17.3 MiB) TX bytes:44556618 (42.4 MiB)
Interrupt:4

eth1 Link encap:Ethernet HWaddr 10:6F:3F:29:70:CC
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:54793 errors:0 dropped:0 overruns:0 frame:0
TX packets:63932 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:40773653 (38.8 MiB) TX bytes:18579083 (17.7 MiB)
Interrupt:5

lo Link encap:Local Loopback
inet addr:127.0.0.1 Mask:255.0.0.0
UP LOOPBACK RUNNING MTU:65536 Metric:1
RX packets:5785 errors:0 dropped:0 overruns:0 frame:0
TX packets:5785 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:0
RX bytes:548628 (535.7 KiB) TX bytes:548628 (535.7 KiB)

pppoe-wan Link encap:Point-to-Point Protocol
inet addr:10.23.115.26 P-t-P:10.23.0.1 Mask:255.255.255.255
UP POINTOPOINT RUNNING NOARP MULTICAST MTU:1492 Metric:1
RX packets:52861 errors:0 dropped:0 overruns:0 frame:0
TX packets:62002 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:3
RX bytes:39494731 (37.6 MiB) TX bytes:17157113 (16.3 MiB)

tun0 Link encap:UNSPEC HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
inet addr:10.7.0.2 P-t-P:10.7.0.2 Mask:255.255.255.0
UP POINTOPOINT RUNNING NOARP MULTICAST MTU:1440 Metric:1
RX packets:206 errors:0 dropped:0 overruns:0 frame:0
TX packets:2805 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:500
RX bytes:28250 (27.5 KiB) TX bytes:213823 (208.8 KiB)

wlan0 Link encap:Ethernet HWaddr 10:6F:3F:29:70:CA
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:1147 errors:0 dropped:0 overruns:0 frame:0
TX packets:1412 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:178347 (174.1 KiB) TX bytes:461178 (450.3 KiB)

请问我哪里可能出了问题？需要怎样解决？谢谢。

**Comment by aa65535** [comment]
使用新的 client script，MTU 改小点试试。

**Comment by 70599** [comment]
感谢回复。

我使用最新拉取自 https://github.com/aa65535/openwrt-shadowvpn 编译的，是最新的吗？

服务端我用ping -s 14xx google.com，测得14xx最大值是1472，再加28应该是1500，所以最后在sv中设成1448了。
客户端我用ping -s 14xx baidu.com，测得14xx最大值是1464，再加28应该是1492，所以最后在sv中设成1440了。
MTU我尝试过的组合1440:1440、1412:1412、1410:1410，都失败了。

请问你有MTU的推荐值吗？

**Comment by 70599** [comment]
改成1350:1350，症状依旧。

**Comment by myliyifei** [comment]
建议开个端口，用iperf3 （要自己编译）  服务器端用  iperf3 发起连接  客户端指定服务器端口之后， 一定要用-R
 让服务器发起反向连接 -u 发起UDP包  -b 指定带宽。 抓包tcpdump看看 GFW干扰

2015-02-07 12:18 GMT+08:00 70599 <notifications@github.com>:

**Comment by 70599** [comment]
楼上的好像比较复杂，暂时没时间搞。

GFW干扰的话，为什么没有影响到同一台VPS上的 ShadowSocks呢？
我pppoe拨号得到的IP是10.23.xx.xx的内网IP，会不会有可能是这里影响到了呢？

**Comment by myliyifei** [comment]
也有可能是运营商对udp  做qos  所以要你测试。  ss是tcp协议
2015年2月7日 下午1:44于 "70599" <notifications@github.com>写道：

**Comment by aa65535** [comment]
即使是内网IP，也是可以使用的，检查一下服务端防火墙。

**Comment by lzokks04** [comment]
今天也遇到了这种症状，ping服务器10.7.0.1正常，本地网移动
客户端ping8.8.8.8不通，服务器tcpdump -i tun0抓包后没发现没有包经过tun0
但是能ping的通8.8.4.4，然后把配置文件的DNS换成8.8.4.4后再连接一切正常
发现连上后一切网页游戏应用正常，然而还是ping不通8.8.8.8
很大几率是因为移动墙中墙orGFW干扰
改一下dns就好了
