### ISSUE TITLE
跟shadowsocks对比测试性能问题

### ISSUE THREAD

**Issue by chijiao** [clowwindy/ShadowVPN#94]
最近对shadowsocks跟shadowvpn进行了性能测试对比.
同局域网100M环境. shadowsocks 加密方式为 AES-256-cfb . 局域网传输1G文件. 
采用 shadowsocks wget 传输文件的速度在 10.7M/s. 加解密CPU使用率为 10%
采用 shadowvpn wget 方式, 为 6.5M/s, 加解密CPU使用率为 30%
采用直接IP, wget 方式为 10.7M/s.  

感觉性能上还是 shadowsocks 要好一些.

**Comment by lsylsy2** [comment]
最近在研究一些其他内核相关的东西，shadowvpn涉及虚拟网卡，在内核与用户态的切换可能会带来不低的消耗。

**Comment by clowwindy** [comment]
无硬件型号，系统，版本，看 CPU 占用率的方法，其他人根本没办法重复和验证你的测试嘛。

**Comment by ddqp** [comment]
可能是MTU问题
