### ISSUE TITLE
希望增加 armhf 版本

### ISSUE THREAD

**Issue by typcn** [clowwindy/ShadowVPN#96]
我的路由器是 armhf 架构，编译炒鸡慢，在树莓派上编译了一个复制过去发现无法运行

**Comment by linhua55** [comment]
你需要交叉编译，这个对你有用吗
https://github.com/aa65535/openwrt-shadowvpn

**Comment by typcn** [comment]
感谢，我找到 toolchain 了

**Comment by Sigma-Algebra** [comment]
树莓派2上直接运行要怎么编译？按readme里的无论apt安装还是编译安装都会失败，是不是和armhf有关

**Comment by typcn** [comment]
我编译很正常啊，你是不是依赖库没装，或者没初始化 submodule

**Comment by Sigma-Algebra** [comment]
后来发现我是没有 cd ~/ShadowVPN/。没怎么用过GitHub源码编译，后来用winscp发现autogen.sh在子目录里，抱着尝试的心态cd到子目录再下手，现在好了
