### ISSUE TITLE
Openwrt启动时执行脚本的权限好像有问题

### ISSUE THREAD

**Issue by gandalfwong** [clowwindy/ShadowVPN#98]
启动时不能自动启动，/var/log/shadowvpn.log报以下错误：
up.info ShadowVPN[840] Get gateway and interface from route table
up.error ShadowVPN[840] Can't get interface from route table
script /etc/shadowvpn/client_up.sh returned non-zero return code: 256

用root登录后手动执行就没问题。 这问题在以前1.3的版本倒是没遇到过。

**Comment by aa65535** [comment]
尝试使用 master 的代码替换 [client_up.sh](https://github.com/clowwindy/ShadowVPN/blob/master/samples/client_up.sh) 和 [client_down.sh](https://github.com/clowwindy/ShadowVPN/blob/master/samples/client_down.sh) .
以前版本没遇到是因为它本身就不会自动启动。
