### ISSUE TITLE
deb包添加对iptables的依赖

### ISSUE THREAD

**Issue by lsylsy2** [clowwindy/ShadowVPN#99]
RT，既然默认脚本使用了iptables，那么就应该算依赖。
实测 nanovz的debian 7 minimal 32bit就没有自带iptables。

**Comment by yy1984** [comment]
nanovz限制这么多，能跑的动shadowvpn吗？

**Comment by myliyifei** [comment]
这个赞同，应该严谨些。
2015年3月6日 下午5:25于 "yy1984" <notifications@github.com>写道：

**Comment by clowwindy** [comment]
赞同。

**Comment by bitwing** [comment]
我原以为 2.4 以上内核都是默认支持的

**Comment by yy1984** [comment]
在openwrt上，如果默认安装了ip-full，就无法安装shadowvpn了，因为它依赖ip
